// examples/frameworks/nuxt/app/pages/emails/send.vue
<script setup lang="ts">
import type { EmailsSendResponse } from "mailchannels-sdk";

const loading = ref(false);
const result = ref<EmailsSendResponse["data"]>();

const sendEmail = async () => {
  loading.value = true;
  $fetch("/api/emails/send", {
    method: "POST"
  }).then((response) => {
    result.value = response;
  }).catch((error) => {
    console.error("Error sending email:", error);
  }).finally(() => {
    loading.value = false;
  });
};
</script>

<template>
  <h1>Send a predefined email</h1>

  <form class="form" @submit.prevent="sendEmail">
    <button type="submit" :disabled="loading">
      {{ loading ? 'Sending...' : 'Send Email' }}
    </button>
  </form>

  <pre v-if="result">{{ JSON.stringify(result, null, 2) }}</pre>
</template>

// examples/frameworks/sveltekit/src/routes/emails/send/+page.svelte
<script lang="ts">
import type { EmailsSendResponse } from "mailchannels-sdk";

let loading = $state(false);
let result = $state<EmailsSendResponse["data"]>();

async function sendEmail (e: SubmitEvent) {
  e.preventDefault();
  loading = true;

  const response = await fetch("/api/emails/send", {
    method: "POST"
  });

  result = await response.json();
  loading = false;
}
</script>

<h1>Send a predefined email</h1>

<form class="form" onsubmit={sendEmail}>
  <button type="submit" disabled={loading}>
    {loading ? "Sending..." : "Send Email"}
  </button>
</form>

{#if result}
  <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}
