// examples/frameworks/nextjs/src/app/emails/send/page.tsx
"use client";

import { useState } from "react";
import type { EmailsSendResponse } from "mailchannels-sdk";

export default function () {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<EmailsSendResponse["data"]>();

  async function sendEmail (e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    setLoading(true);

    const response = await fetch("/api/emails/send", {
      method: "POST"
    });

    const data = await response.json();

    setResult(data);
    setLoading(false);
  }

  return (
    <>
      <h1>Send a predefined email</h1>

      <form className="form" onSubmit={sendEmail}>
        <button type="submit" disabled={loading}>
          {loading ? "Sending..." : "Send Email"}
        </button>
      </form>

      {result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}
    </>
  );
}

// examples/frameworks/sveltekit/src/routes/emails/send/+page.svelte
<script lang="ts">
import type { EmailsSendResponse } from "mailchannels-sdk";

let loading = $state(false);
let result = $state<EmailsSendResponse["data"]>();

async function sendEmail (e: SubmitEvent) {
  e.preventDefault();
  loading = true;

  const response = await fetch("/api/emails/send", {
    method: "POST"
  });

  result = await response.json();
  loading = false;
}
</script>

<h1>Send a predefined email</h1>

<form class="form" onsubmit={sendEmail}>
  <button type="submit" disabled={loading}>
    {loading ? "Sending..." : "Send Email"}
  </button>
</form>

{#if result}
  <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}
