// examples/frameworks/nextjs/src/app/emails/send-attachment/page.tsx
"use client";

import { type ChangeEvent, useState } from "react";
import type { EmailsSendResponse } from "mailchannels-sdk";

export default function () {
  const [to, setTo] = useState("");
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [filename, setFilename] = useState("");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<EmailsSendResponse["data"]>();

  async function sendEmail (e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!(file instanceof File)) {
      alert("Attachment file is required.");
      return;
    }

    const formData = new FormData();
    formData.append("payload", JSON.stringify({ to, subject, message, filename }));
    formData.append("file", file);

    setLoading(true);

    const response = await fetch("/api/emails/send-attachment", {
      method: "POST",
      body: formData
    });

    const data = await response.json();

    setResult(data);
    setLoading(false);
  }

  const addFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const target = event.target as HTMLInputElement;
    if (target.files && target.files.length > 0) {
      setFile(target.files[0] ?? null);
    }
  };

  return (
    <>
      <h1>Send an email with an attachment</h1>

      <form className="form" onSubmit={sendEmail}>
        <div className="input">
          <label htmlFor="to">To:</label>
          <input
            id="to"
            name="to"
            type="email"
            placeholder="to@example.com"
            value={to}
            onChange={e => setTo(e.target.value)}
            required
          />
        </div>
        <div className="input">
          <label htmlFor="subject">Subject:</label>
          <input
            id="subject"
            name="subject"
            type="text"
            placeholder="Your email subject"
            value={subject}
            onChange={e => setSubject(e.target.value)}
            required
          />
        </div>
        <div className="input">
          <label htmlFor="message">Message:</label>
          <textarea
            id="message"
            name="message"
            placeholder="Write a message"
            value={message}
            onChange={e => setMessage(e.target.value)}
            required
          />
        </div>
        <div className="input">
          <label htmlFor="file">Attachment File:</label>
          <input
            id="file"
            name="file"
            type="file"
            onChange={e => addFile(e)}
            required
          />
        </div>
        <div className="input">
          <label htmlFor="filename">Attachment Filename:</label>
          <input
            id="filename"
            name="filename"
            type="text"
            placeholder="image.jpg"
            value={filename}
            onChange={e => setFilename(e.target.value)}
            required
          />
        </div>
        <button type="submit" disabled={loading}>
          {loading ? "Sending..." : "Send Email"}
        </button>
      </form>

      {result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}
    </>
  );
}

// examples/frameworks/sveltekit/src/routes/emails/send-attachment/+page.svelte
<script lang="ts">
import type { EmailsSendResponse } from "mailchannels-sdk";

const form = $state({
  to: "",
  subject: "",
  message: "",
  file: null as File | null,
  filename: ""
});

let loading = $state(false);
let result = $state<EmailsSendResponse["data"]>();

async function sendEmail (e: SubmitEvent) {
  e.preventDefault();
  const { file, ...data } = form;

  if (!(file instanceof File)) {
    alert("Attachment file is required.");
    return;
  }

  const formData = new FormData();
  formData.append("payload", JSON.stringify(data));
  formData.append("file", file);

  loading = true;

  const response = await fetch("/api/emails/send-attachment", {
    method: "POST",
    body: formData
  });

  result = await response.json();
  loading = false;
}

const addFile = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  if (target.files && target.files.length > 0) {
    form.file = target.files[0] ?? null;
  }
};
</script>

<h1>Send an email with an attachment</h1>

<form class="form" onsubmit={sendEmail}>
  <div class="input">
    <label for="to">To:</label>
    <input
      id="to"
      name="to"
      type="email"
      placeholder="to@example.com"
      bind:value={form.to}
      required
    >
  </div>
  <div class="input">
    <label for="subject">Subject:</label>
    <input
      id="subject"
      name="subject"
      type="text"
      placeholder="Your email subject"
      bind:value={form.subject}
      required
    >
  </div>
  <div class="input">
    <label for="message">Message:</label>
    <textarea
      id="message"
      name="message"
      placeholder="Write a message"
      bind:value={form.message}
      required
    >
    </textarea>
  </div>
  <div class="input">
    <label for="file">Attachment File:</label>
    <input
      id="file"
      name="file"
      type="file"
      onchange={addFile}
      required
    >
  </div>
  <div class="input">
    <label for="filename">Attachment Filename:</label>
    <input
      id="filename"
      name="filename"
      type="text"
      placeholder="image.jpg"
      bind:value={form.filename}
      required
    >
  </div>
  <button type="submit" disabled={loading}>
    {loading ? "Sending..." : "Send Email"}
  </button>
</form>

{#if result}
  <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}
