// examples/frameworks/sveltekit/src/routes/webhooks/delete-all/+page.svelte
<script lang="ts">
let loading = $state(false);
let result = $state<{ success: boolean }>();

async function deleteAllWebhooks (e: SubmitEvent) {
  e.preventDefault();
  loading = true;

  const response = await fetch("/api/webhooks", {
    method: "DELETE",
    headers: { "Content-Type": "application/json" }
  });

  result = await response.json();
  loading = false;
}
</script>

<h1>Delete all webhooks</h1>

<form class="form" onsubmit={deleteAllWebhooks}>
  <button type="submit" disabled={loading}>
    {loading ? "Deleting..." : "Delete All"}
  </button>
</form>

{#if result}
  <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}

// examples/frameworks/nextjs/src/app/webhooks/delete-all/page.tsx
"use client";

import { useState } from "react";

export default function () {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ success: boolean }>();

  async function deleteAllWebhooks (e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    setLoading(true);

    const response = await fetch("/api/webhooks", {
      method: "DELETE",
      headers: { "Content-Type": "application/json" }
    });

    const data = await response.json();

    setResult(data);
    setLoading(false);
  }

  return (
    <>
      <h1>Delete all webhooks</h1>

      <form className="form" onSubmit={deleteAllWebhooks}>
        <button type="submit" disabled={loading}>
          {loading ? "Deleting..." : "Delete All"}
        </button>
      </form>

      {result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}
    </>
  );
}
