// examples/frameworks/nextjs/src/app/webhooks/list/page.tsx
"use client";

import { useState } from "react";
import type { WebhooksListResponse } from "mailchannels-sdk";

export default function () {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<WebhooksListResponse["data"]>();

  async function fetchWebhooks (e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    setLoading(true);

    const response = await fetch("/api/webhooks", {
      headers: { "Content-Type": "application/json" }
    });

    const data = await response.json();

    setResult(data);
    setLoading(false);
  }

  return (
    <>
      <h1>List webhooks</h1>

      <form className="form" onSubmit={fetchWebhooks}>
        <button type="submit" disabled={loading}>
          {loading ? "Fetching..." : "Get webhooks"}
        </button>
      </form>

      {result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}
    </>
  );
}

// examples/frameworks/sveltekit/src/routes/webhooks/list/+page.svelte
<script lang="ts">
import type { WebhooksListResponse } from "mailchannels-sdk";

let loading = $state(false);
let result = $state<WebhooksListResponse["data"]>();

async function fetchWebhooks (e: SubmitEvent) {
  e.preventDefault();
  loading = true;

  const response = await fetch("/api/webhooks", {
    headers: { "Content-Type": "application/json" }
  });

  result = await response.json();
  loading = false;
}
</script>

<h1>List webhooks</h1>

<form class="form" onsubmit={fetchWebhooks}>
  <button type="submit" disabled={loading}>
    {loading ? "Fetching..." : "Get webhooks"}
  </button>
</form>

{#if result}
  <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}
