// examples/frameworks/sveltekit/src/routes/webhooks/create/+page.svelte
<script lang="ts">
const form = $state({
  endpoint: ""
});

let loading = $state(false);
let result = $state<{ success: boolean }>();

async function createWebhook (e: SubmitEvent) {
  e.preventDefault();
  loading = true;

  const response = await fetch("/api/webhooks", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(form)
  });

  result = await response.json();
  loading = false;
}
</script>

<h1>Create a webhook</h1>

<form class="form" onsubmit={createWebhook}>
  <div class="input">
    <label for="endpoint">Endpoint:</label>
    <input
      id="endpoint"
      name="endpoint"
      type="url"
      placeholder="https://example.com/webhooks"
      bind:value={form.endpoint}
      required
    >
  </div>
  <button type="submit" disabled={loading}>
    {loading ? "Creating..." : "Create"}
  </button>
</form>

{#if result}
  <pre>{JSON.stringify(result, null, 2)}</pre>
{/if}

// examples/frameworks/nuxt/app/pages/webhooks/create.vue
<script setup lang="ts">
const form = ref({
  endpoint: ""
});

const loading = ref(false);
const result = ref<{ success: boolean }>();

const createWebhook = async () => {
  loading.value = true;
  $fetch("/api/webhooks", {
    method: "POST",
    body: form.value
  }).then((response) => {
    result.value = response;
  }).catch((error) => {
    console.error("Error creating webhook:", error);
  }).finally(() => {
    loading.value = false;
  });
};
</script>

<template>
  <h1>Create a webhook</h1>

  <form class="form" @submit.prevent="createWebhook">
    <div class="input">
      <label for="endpoint">Endpoint:</label>
      <input id="endpoint" v-model="form.endpoint" type="url" placeholder="https://example.com/webhooks" required>
    </div>
    <button type="submit" :disabled="loading">
      {{ loading ? 'Creating...' : 'Create' }}
    </button>
  </form>

  <pre v-if="result">{{ JSON.stringify(result, null, 2) }}</pre>
</template>
